{
  "uid" : "6404c4b168f8afd9",
  "name" : "someFailingTestsWithDataProvider",
  "fullName" : "test.java.tests.DummyTest.someFailingTestsWithDataProvider",
  "historyId" : "6f1486d7d0cecb5aa22973477b82de55",
  "time" : {
    "start" : 1605988953875,
    "stop" : 1605988953876,
    "duration" : 1
  },
  "status" : "failed",
  "statusMessage" : "expected [2] but found [1]",
  "statusTrace" : "java.lang.AssertionError: expected [2] but found [1]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:839)\r\n\tat org.testng.Assert.assertEquals(Assert.java:849)\r\n\tat test.java.tests.DummyTest.someFailingTestsWithDataProvider(DummyTest.java:29)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)\r\n\tat java.base/java.lang.Thread.run(Thread.java:832)\r\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "setUp",
    "time" : {
      "start" : 1605988947490,
      "stop" : 1605988953872,
      "duration" : 6382
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "afterStages" : [ {
    "name" : "tearDown",
    "time" : {
      "start" : 1605988954504,
      "stop" : 1605988955149,
      "duration" : 645
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "labels" : [ {
    "name" : "package",
    "value" : "test.java.tests.DummyTest"
  }, {
    "name" : "testClass",
    "value" : "test.java.tests.DummyTest"
  }, {
    "name" : "testMethod",
    "value" : "someFailingTestsWithDataProvider"
  }, {
    "name" : "parentSuite",
    "value" : "Lesson11"
  }, {
    "name" : "suite",
    "value" : "Failing dummy tests"
  }, {
    "name" : "subSuite",
    "value" : "test.java.tests.DummyTest"
  }, {
    "name" : "host",
    "value" : "XPS7"
  }, {
    "name" : "thread",
    "value" : "32076@XPS7.TestNG-test=Failing dummy tests-1(17)"
  }, {
    "name" : "framework",
    "value" : "testng"
  }, {
    "name" : "language",
    "value" : "java"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "arg0",
    "value" : "1"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "6404c4b168f8afd9.json",
  "parameterValues" : [ "1" ]
}